AdExNetwork/adex-validator-stack-rust

- Cargo.lock
- domain/Cargo.toml
- domain/src/balances_map.rs
- domain/src/big_num.rs
- domain/src/lib.rs
Resolves #99 ~but still needs **testing**~ and the tests from the JS implementation were implemented.
> Issue #99 Applying validators fees

- validator/src/application/message_propagation.rs
- validator/src/domain/validator.rs
- validator/src/infrastructure/persistence/validator/memory.rs
> Issue #106

- Cargo.lock
- domain/src/balances_map.rs
- domain/src/big_num.rs
- validator/Cargo.toml
- validator/src/domain.rs
- validator/src/domain/event.rs
> Issue #102 mergeAggrs and mergePayoutsIntoBalances

- Cargo.lock
- Cargo.toml
- adview-manager/Cargo.toml
- adview-manager/src/lib.rs
- primitives/src/ad_unit.rs
- primitives/src/channel.rs
- primitives/src/lib.rs
- primitives/src/market_channel.rs
- primitives/src/targeting_tag.rs
> Issue #100 adview manager logic

- primitives/src/channel.rs
- primitives/src/channel_fixtures.rs
- primitives/src/targeting_tag.rs
- primitives/src/util.rs
- primitives/src/validator.rs
- validator_worker/src/core.rs
- validator_worker/src/core/follower_rules.rs
- validator_worker/src/lib.rs
Resolves #119 
- Only required for those test (the is_healthy & is_valid_transaction tests) fixtures and code was uncommented/re-added
- the HEALTH_THRESHOLD_NEG is passed as function argument as samparsky suggested
> Issue 119 migrate is healthy and is valid transaction

- validator_worker/src/core/fees.rs
> Issue #113 remove distribution struct

- .travis.yml
- adapter/src/ethereum.rs
- adapter/src/lib.rs
- adview-manager/src/lib.rs
- primitives/src/big_num.rs
- rust-toolchain
- validator_worker/src/main.rs
- Fixes `rustfmt` & `clippy` warnings
- Locks `nightly` version on `travis` and `rust-toolchain`
> Lock nightly and fix some warnings

- Cargo.lock
- primitives/src/adapter.rs
- primitives/src/sentry.rs
- validator_worker/Cargo.toml
- validator_worker/src/follower.rs
- validator_worker/src/heartbeat.rs
- validator_worker/src/leader.rs
- validator_worker/src/lib.rs
- validator_worker/src/main.rs
- validator_worker/src/producer.rs
- validator_worker/src/sentry_interface.rs
> fix: validator worker startup

- adview-manager/src/lib.rs
Related to the fixes in commits:
- https://github.com/AdExNetwork/adex-adview-manager/commit/47bd1589db7aad3dc7b6db9330766ced7279c849
- https://github.com/AdExNetwork/adex-adview-manager/commit/f062caed0053f2d501cea21dfa02105e957e148c (this doesn't apply since we use `truncate()` on the `by_score` is we already returned the top ones)
> Crititcal Bugix: Adview manager filter before slicing

- primitives/src/merkle_tree.rs
- validator_worker/src/follower.rs
> Issue 168 fix merkle tree bug

- adapter/src/dummy.rs
- adapter/src/ethereum.rs
- primitives/src/adapter.rs
> Issue #176 `EthereumAdapter::session_from_token` mutability

- Cargo.lock
- adapter/src/dummy.rs
- adapter/src/ethereum.rs
- primitives/src/adapter.rs
- validator_worker/Cargo.toml
- validator_worker/src/follower.rs
- validator_worker/src/heartbeat.rs
- validator_worker/src/leader.rs
- validator_worker/src/lib.rs
- validator_worker/src/main.rs
- validator_worker/src/sentry_interface.rs
Fixes #174 `get_auth`
* Removes RwLock for Adapter
* Fixes #180 `unlock` adapter bug
> Fix get auth

- .cargo/config
- Cargo.lock
- adapter/Cargo.toml
- adapter/src/ethereum.rs
- sentry/Cargo.toml
- sentry/src/access.rs
- sentry/src/db.rs
- sentry/src/lib.rs
- sentry/src/main.rs
- sentry/src/middleware/auth.rs
- https://github.com/khuey/bb8 - of the branch for this PR https://github.com/khuey/bb8/pull/37
- Updates the parity dependencies as they were moved around
- Fixes code after changes on redis-rs branch of async
> Updates dependencies and adds bb8

- Cargo.lock
- adapter/src/ethereum.rs
- primitives/Cargo.toml
- primitives/src/channel.rs
- sentry/src/chain.rs
- sentry/src/event_reducer.rs
- sentry/src/lib.rs
- sentry/src/main.rs
- sentry/src/middleware/channel.rs
- sentry/src/routes/cfg.rs
- sentry/src/routes/channel.rs
> Refactor route, fix POST /channel

- adapter/src/dummy.rs
- adapter/src/ethereum.rs
- primitives/src/channel.rs
- primitives/src/channel_validator.rs
- primitives/src/config.rs
- sentry/src/chain.rs
- sentry/src/db.rs
- sentry/src/db/channel.rs
- sentry/src/lib.rs
- sentry/src/middleware/channel.rs
- sentry/src/routes/channel.rs
Resolves #189 
- Fixes `channel_load` (channel_load & channel_if_exist )
- impl `channel_if_active`
- GET /channel/:id/status
- impl ToSql for ChannelSpec
- sentry - moves insert query to `db/channel`
- removes unused Config identity from ChannelValidator and accepts a ValidatorId directly (passed from the Adapter)
Channel creating is tested and working!
> Issue #189 channel if functions

- primitives/src/sentry.rs
Add the Click event to primitives
> add Click event to primitives

- validator_worker/src/follower.rs
- validator_worker/src/lib.rs
- validator_worker/src/main.rs
- validator_worker/src/sentry_interface.rs
> Issue #213 Redundant `whoami` where we have `Adapter` + #210 #212

- adapter/src/dummy.rs
- adapter/src/ethereum.rs
> fix: add event_loop handle to etheruem_adapter

- Cargo.lock
- Cargo.toml
- adapter/src/ethereum.rs
- adapter/src/lib.rs
- primitives/Cargo.toml
- primitives/src/channel.rs
- primitives/src/channel_validator.rs
- primitives/src/config.rs
- primitives/src/sentry.rs
- primitives/src/util/tests/prep_db.rs
- sentry/src/access.rs
- sentry/src/db.rs
- sentry/src/db/event_aggregate.rs
- sentry/src/event_reducer.rs
- sentry/src/lib.rs
- sentry/src/middleware/auth.rs
- sentry/src/middleware/event_aggregate.rs
- sentry/src/routes/analytics.rs
- sentry/src/routes/event_aggregate.rs
> Issue #9 GET Channel Events aggregates

- Cargo.lock
- validator_worker/Cargo.toml
- validator_worker/src/main.rs
- validator_worker/src/sentry_interface.rs
Updating to stable releases :tada:
> Update validator_worker dependencies

- .dockerignore
- Cargo.lock
- Cargo.toml
- Dockerfile
- adapter/Cargo.toml
- docker-compose.yml
- sentry/Cargo.toml
- validator.env.dist
> Issue #233 validator worker docker image

- adapter/src/dummy.rs
- adapter/src/ethereum.rs
- primitives/src/balances_map.rs
- primitives/src/lib.rs
- primitives/src/sentry.rs
- primitives/src/validator.rs
- sentry/src/access.rs
- sentry/src/event_reducer.rs
- validator_worker/src/core/events.rs
- validator_worker/src/core/fees.rs
- validator_worker/src/core/follower_rules.rs
- validator_worker/src/lib.rs
- validator_worker/src/sentry_interface.rs
Resolves #235 
- Added ToETHChecksum trait
- `BalancesMap` now has `ValidatorId` as key
- Event payouts and etc. also have `ValidatorId` as key
> Issue #235 checksummed validator

- .travis.yml
- Cargo.lock
- README.md
- primitives/src/channel.rs
- sentry/src/main.rs
- sentry/src/routes/analytics.rs
- validator_worker/Cargo.toml
- validator_worker/src/lib.rs
- validator_worker/src/main.rs
- validator_worker/src/producer.rs
- validator_worker/src/sentry_interface.rs
Resolves #105 
Tackles the logging listed in the comments:
https://github.com/AdExNetwork/adex-validator-stack-rust/issues/105#issuecomment-566454432
https://github.com/AdExNetwork/adex-validator-stack-rust/issues/105#issuecomment-574068843
> Issue #105 validator worker logging

- Cargo.lock
- adapter/Cargo.toml
- adapter/src/ethereum.rs
- docs/config/dev.toml
- docs/config/prod.toml
- primitives/src/config.rs
- primitives/src/lib.rs
Resolves #243 
Changes applied from: https://github.com/AdExNetwork/adex-validator/pull/250
> Issue #243 contrafactual accounts

- sentry/src/access.rs
- sentry/src/db/analytics.rs
- sentry/src/db/channel.rs
> Issue #245 Avoid time-sensitive tests

- sentry/src/chain.rs
- sentry/src/db/channel.rs
- sentry/src/lib.rs
- sentry/src/routes/channel.rs
Adds /:id/validator-messages POST route
> Validator messages

- sentry/migrations/20190806011140_initial-tables/up.sql
> fix: time postgres precision

- docs/config/prod.toml
- validator_worker/src/sentry_interface.rs
Pagination when retrieving channels: return them in the proper order
cfg: update based on latest cfg in the JS impl
> Cfg and pagination

- primitives/src/util/tests/prep_db.rs
- sentry/src/main.rs
- validator_worker/src/main.rs
Resolves #266 
Adds changes to Dummy Channel to align with the JS impl.
> Issue #266 long cmd arguments

- adapter/src/ethereum.rs
- adapter/src/ethereum/error.rs
- primitives/src/adapter.rs
- validator_worker/src/core/events.rs
- validator_worker/src/error.rs
- validator_worker/src/follower.rs
- validator_worker/src/heartbeat.rs
- validator_worker/src/leader.rs
- validator_worker/src/producer.rs
> Couple of fixes PR #277; original message

- primitives/src/targeting/eval.rs
> Math functions from AIP#31

- primitives/src/ad_slot.rs
- primitives/src/sentry.rs
- primitives/src/targeting.rs
- primitives/src/targeting/eval.rs
- sentry/src/db/event_aggregate.rs
- sentry/src/routes/channel.rs
- Resolves #303 
- typos
- other fixes
> Supermarket changes

- sentry/src/access.rs
- sentry/src/event_reducer.rs
- sentry/src/middleware/auth.rs
- sentry/src/payout.rs
> fix: remove uneeded clones

- adview-manager/src/lib.rs
- primitives/src/balances_map.rs
- primitives/src/big_num.rs
- primitives/src/config.rs
- validator_worker/src/producer.rs
> Hotfix #315 Do not allow empty Accounting, skip them instead

- Cargo.lock
- adapter/src/lib.rs
- primitives/Cargo.toml
- primitives/src/merkle_tree.rs
- sentry/src/db.rs
- sentry/src/event_aggregator.rs
- sentry/src/event_reducer.rs
- sentry/src/middleware/auth.rs
- validator_worker/src/heartbeat.rs
- validator_worker/src/lib.rs
> Hotfix #316 MerkleTree missing 0 leaves check

- Cargo.lock
- adapter/src/lib.rs
- primitives/Cargo.toml
- primitives/src/balances_map.rs
- primitives/src/merkle_tree.rs
- sentry/src/db.rs
- sentry/src/event_aggregator.rs
- sentry/src/event_reducer.rs
- validator_worker/src/core/fees.rs
- validator_worker/src/follower.rs
- validator_worker/src/heartbeat.rs
- validator_worker/src/leader.rs
- validator_worker/src/lib.rs
- validator_worker/src/producer.rs
> Merge master into dev

- primitives/src/targeting.rs
- primitives/src/targeting/eval.rs
- primitives/src/targeting/eval_test.rs
This is the last task that closes #296 
Part of [AIP#31](https://github.com/AdExNetwork/aips/issues/31)
> AIP#31 Issue #296 Function::Get should work with output

- LICENSE
Resolve https://github.com/AdExNetwork/organization/issues/31
> LICENSE - use AGPL instead of GPL

- primitives/src/sentry.rs
- sentry/src/db/channel.rs
- sentry/src/routes/channel.rs
> Issue 337 align channellist response

- adview-manager/src/lib.rs
- primitives/src/sentry.rs
- primitives/src/targeting/eval.rs
- sentry/src/routes/channel.rs
> no heartbeats in response when query param is not provided

- primitives/src/channel.rs
- primitives/src/sentry.rs
Fixes issue introduced in PR #344 for issue #343
> Bugfix ChannelId

- Cargo.lock
- adapter/Cargo.toml
- adapter/src/ethereum.rs
> Mock relayer request for session from token
